    scalar JSON
    
    # /v1

    type ApiEndpoint {
        method: String!
        path: String!
        url: String!
    }

    """
    Main entry point to make any type of query or mutation of your api and its resources
    """
    type Query {
        api: [APIRequest],
    }

    # /api
    """
    A request to your resources / services (GraphQL Scripts, AWS, MongoDB, NextJs, Ledger)
    """
    type APIRequest {
        """
        Make a request to GraphQL Scripts Endpoint
        """
        graphql: GraphQLScriptRequest
        """
        Query and mutate AWS resources and services
        """
        aws: AWSRequest
        """
        Connect, query, and mutate a MongoDB instance
        """
        mongodb: MongoDBRequest
        """
        Initialize and manage a front-end NextJs application
        """
        nextjs: NextJsRequest
        """
        View evirnomnents, secrets, events, and architecture related to your api 
        """
        ledger: LedgerRequest
    }


    # /v1/api/graphqlscripts

    type GraphQLScriptRequest {
        create(name: String!): CreateGraphQLScriptRequest
        delete(nameID: String!): DeleteGraphQLScriptRequest
        execute(nameID: String!): ExecuteGraphQLScriptRequest
    }

        # /v1/api/graphqlscripts/create/:graphqlscriptsname
        type CreateGraphQLScriptRequest {
            name: String
            nameID: String!
            apiendpoint: ApiEndpoint
        }

        # /v1/api/graphqlscripts/delete/:graphqlscriptsnameID
        type DeleteGraphQLScriptRequest {
            name: String
            nameID: String
            apiendpoint: ApiEndpoint

            ### more
        }

        # /v1/api/graphqlscripts/execute/:graphqlscriptsnameID
        type ExecuteGraphQLScriptRequest {
            name: String
            nameID: String
            apiendpoint: ApiEndpoint

            ### more
        }

 

    # /v1/api/aws

    type AWSRequest {
        create: AWSCreateResource
        delete: AWSDeleteResource
        apigateway(nameID: String!): AWSApiGatewayResourceManager
        websocket(nameID: String!): AWSWebsocketResourceManager
    }

        # /v1/api/aws/create
        type AWSCreateResource {
            apigateway(name: String!): AWSCreateApiGateway
            websocket(name: String!): AWSCreateWebsocket
        }

            # /v1/api/aws/create/apigateway/:apigatewayname
            type AWSCreateApiGateway {
                name: String
                nameID: String!
            }

            # /v1/api/aws/create/websocket/:websocketname
            type AWSCreateWebsocket {
                name: String
                nameID: String!
            }

        # /v1/api/aws/delete
        type AWSDeleteResource {
            apigateway(nameID: String!): AWSDeleteApiGateway
            websocket(nameID: String!): AWSDeleteWebsocket
        }

            # /v1/api/aws/delete/apigateway/:apigatewaynameID
            type AWSDeleteApiGateway {
                name: String
                nameID: String!

                ### more
            }

            # /v1/api/aws/delete/websocket/:websocketnameID
            type AWSDeleteWebsocket {
                name: String
                nameID: String!

                ### more
            }

    
        # /v1/api/aws/apigateway/:apigatewaynameID
        type AWSApiGatewayResourceManager {
            create: AWSCreateApiGatewayResource
            delete: AWSDeleteApiGatewayResource
            dynamodb(nameID: String!): AWSDynamoDBResourceManager
            s3(nameID: String!): AWSS3ResourceManager
            lambda(nameID: String!): AWSLambdaResourceManager
        }

            # /v1/api/aws/apigateway/:apigatewaynameID/create
            type AWSCreateApiGatewayResource {
                dynamodb(name: String): AWSCreateDynamoDB
                s3(name: String): AWSCreateS3
                lambda(name: String): AWSCreateLambda
            }

                # /v1/api/aws/apigateway/:apigatewaynameID/create/dynamodb/:dynamodbname
                type AWSCreateDynamoDB {
                    name: String
                    nameID: String!
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/create/s3/:s3name
                type AWSCreateS3 {
                    name: String
                    nameID: String!
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/create/lambda/:lambdaname
                type AWSCreateLambda {
                    name: String
                    nameID: String!
                }

            # /v1/api/aws/apigateway/:apigatewaynameID/delete
            type AWSDeleteApiGatewayResource {
                dynamodb(nameID: String!): AWSDeleteDynamoDB
                s3(nameID: String!): AWSDeleteS3
                lambda(nameID: String!): AWSDeleteLambda
            }

                # /v1/api/aws/apigateway/:apigatewaynameID/delete/dynamodb/:dynamodbnameID
                type AWSDeleteDynamoDB {
                    name: String
                    nameID: String!

                    ### more
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/delete/s3/:s3nameID
                type AWSDeleteS3 {
                    name: String
                    nameID: String!

                    ### more
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/delete/lambda/:lambddanameID
                type AWSDeleteLambda {
                    name: String
                    nameID: String!

                    ### more
                }

            # /v1/api/aws/apigateway/:apigatewaynameID/dynamodb/:dynamodbnameID
            type AWSDynamoDBResourceManager {
                name: String
                nameID: String
                apiendpoint: ApiEndpoint

                ### more
            }

            # /v1/api/aws/apigateway/:apigatewaynameID/s3/:s3nameID
            type AWSS3ResourceManager {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/aws/apigateway/:apigatewaynameID/lambda/:lambdanameID
            type AWSLambdaResourceManager {
                read: AWSLambdaResourceRead
                update: AWSLambdaResourceUpdate
                execute: AWSLambdaResourceExecute
            }

                # /v1/api/aws/apigateway/:apigatewaynameID/lambda/:lambdanameID/read
                type AWSLambdaResourceRead {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/lambda/:lambdanameID/update
                type AWSLambdaResourceUpdate {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/aws/apigateway/:apigatewaynameID/lambda/:lambdanameID/execute
                type AWSLambdaResourceExecute {
                    name: String
                    nameID: String

                    ### more
                }


        # /v1/api/aws/websocket/:websocketnameID
        type AWSWebsocketResourceManager {
            name: String
            nameID: String

            ### more
        }

    # /v1/api/mongodb

    type MongoDBRequest {
        create(name: String!): CreateMongoDB
        delete(nameID: String!): DeleteMongoDB
        db(nameID: String!): MongoDBResourceManager
        script: MongoDBResourceScript

    }

        # /v1/api/mongodb/create/:mongodbname
        type CreateMongoDB {
            name: String
            nameID: String!
        }

        # /v1/api/mongodb/delete/:mongodbnameID
        type DeleteMongoDB {
            name: String
            nameID: String!

            ### more
        }

        # /v1/api/mongodb/:mongodbnameID
        type MongoDBResourceManager {
            name: String
            nameID: String
        }

        # /v1/api/mongodb/script
        type MongoDBResourceScript {
            execute(mongodbscript: String!): MongoDBResourceScriptResponse
            executegraphql(mongodbscriptbuild: MongoDBResourceScriptBuildRoot): MongoDBResourceScriptResponse
        }

            type MongoDBResourceScriptResponse {
                status: String!
                variables: String!
                apiendpoint: ApiEndpoint
            }

            input MongoDBResourceScriptBuildRoot {
                MongoDBName: String!
                MongoDB: MongoDBResourceScriptRoot!
            }

                input MongoDBResourceScriptRoot {
                    root: Boolean!
                    chain: [MongoDBResourceScriptRequest!]!
                }

                    input MongoDBResourceScriptRequest {
                        method: String!
                        args: JSON
                        variable: MongoDBResourceScriptRequestVariable
                        chain: [MongoDBResourceScriptRequest]
                    }

                        input MongoDBResourceScriptRequestVariable {
                            name: String!
                            return: Boolean!
                        }





    # /v1/api/nextjs

    type NextJsRequest {
        create(name: String!): CreateNextJsResource
        delete(nameID: String!): DeleteNextJsResource
        resource(nameID: String!): NextJsResourceManager
    }

        # /v1/api/nextjs/create/:nextjsname
        type CreateNextJsResource {
            name: String
            nameID: String!
        }

        # /v1/api/nextjs/delete/:nextjsnameID
        type DeleteNextJsResource {
            name: String
            nameID: String!
        }

        # /v1/api/nextjs/:nextjsnameID
        type NextJsResourceManager {
            name: String
            nameID: String!

            ### more
        }


    # /v1/api/ledger

    type LedgerRequest {
        environmentVariables: AppEnvironmentVariablesLedger
        secrets(secretApiKey: String!): AppSecretsLedger
        events: AppEventsLedger
        architecture: AppArchitectureLedger
    }

        # /v1/api/ledger/environmentvariables
        type AppEnvironmentVariablesLedger {
            api: APIEnvironmenVariablesLedger
            ec2(nameID: String): [EC2EnvironmentVariablesLedger]
            apigateway(nameID: String): [ApiGatewayEnvironmentVariablesLedger]
            websocket(nameID: String): [WebsocketEnvironmentVariablesLedger]
            mongodb(nameID: String): [MongoDBEnvironmentVariablesLedger]
            nextjs(nameID: String): [NextJsEnvironmentVariablesLedger]
        }

            # /v1/api/ledger/environmentvariables/api
            type APIEnvironmenVariablesLedger {
                rid: String

                ### more
            }

            # /v1/api/ledger/environmentvariables/ec2
            # /v1/api/ledger/environmentvariables/ec2/:ec2nameID
            type EC2EnvironmentVariablesLedger {
                name: String
                nameID: String
                id: String

                ### more
            }

            # /v1/api/ledger/environmentvariables/apigateway
            # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID
            type ApiGatewayEnvironmentVariablesLedger {
                name: String
                nameID: String
                dynamodb(nameID: String): [DynamoEnvironmentVariablesLedger]
                s3(nameID: String): [S3SEnvironmentVariablesLedger]
                lambda(nameID: String): [LambdaEnvironmentVariablesLedger]

                ### more
            }

                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/dynamodb
                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/dynamodb/:dynamodbnameID
                type DynamoEnvironmentVariablesLedger {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/s3
                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/s3/:s3nameID
                type S3SEnvironmentVariablesLedger {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/lambda
                # /v1/api/ledger/environmentvariables/apigateway/:apigatewaynameID/lambda/:lambdanameID
                type LambdaEnvironmentVariablesLedger {
                    name: String
                    nameID: String

                    ### more
                }

            # /v1/api/ledger/environmentvariables/websocket
            # /v1/api/ledger/environmentvariables/websocket/:websocketnameID
            type WebsocketEnvironmentVariablesLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/environmentvariables/mongodb
            # /v1/api/ledger/environmentvariables/mongodb/:mongodbnameID
            type MongoDBEnvironmentVariablesLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/environmentvariables/nextjs
            # /v1/api/ledger/environmentvariables/nextjs/:nextjsnameID
            type NextJsEnvironmentVariablesLedger {
                name: String
                nameID: String

                ### more
            }

        # /v1/api/ledger/secrets
        type AppSecretsLedger {
            api: APISecretsLedger
            ec2(nameID: String): [EC2SecretsLedger]
            apigateway(nameID: String): [ApiGatewaySecretsLedger]
            websocket(nameID: String): [WebsocketSecretsLedger]
            mongodb(nameID: String): [MongoDBSecretsLedger]
            nextjs(nameID: String): [NextJsSecretsLedger]
        }

            # /v1/api/ledger/secrets/api
            type APISecretsLedger {
                apiKey: String

                ### more
            }

            # /v1/api/ledger/secrets/ec2
            # /v1/api/ledger/secrets/ec2/:ec2nameID
            type EC2SecretsLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/secrets/apigateway
            # /v1/api/ledger/secrets/apigateway/:apigatewaynameID
            type ApiGatewaySecretsLedger {
                name: String
                nameID: String
                dynamodb(nameID: String): [DynamoDBSecretsLedger]
                s3(nameID: String): [S3SecretsLedger]
                lambda(nameID: String): [LambdaSecretsLedger]

                ### more
            }

                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/dynamodb
                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/dynamodb/:dynamodbnameID
                type DynamoDBSecretsLedger {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/s3
                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/s3/:s3nameID
                type S3SecretsLedger {
                    name: String
                    nameID: String

                    ### more
                }

                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/lambda
                # /v1/api/ledger/secrets/apigateway/:apigatewaynameID/lambda/:lambdanameID
                type LambdaSecretsLedger {
                    name: String
                    nameID: String

                    ### more
                }

            # /v1/api/ledger/secrets/websocket
            # /v1/api/ledger/secrets/websocket/:websocketnameID
            type WebsocketSecretsLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/secrets/mongodb
            # /v1/api/ledger/secrets/mongodb/:mongodbnameID
            type MongoDBSecretsLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/secrets/nextjs
            # /v1/api/ledger/secrets/nextjs/:nextjsnameID
            type NextJsSecretsLedger {
                name: String
                nameID: String

                ### more
            }

        # /v1/api/ledger/events
        type AppEventsLedger {
            api: APIEventsLedger
            graphqlscripts(nameID: String): [GraphQLScriptsEventsLedger] 
            ec2(nameID: String): [EC2EventsLedger]
            apigateway(nameID: String): [ApiGatewayEventsLedger]
            websocket(nameID: String): [WebsocketEventsLedger]
            mongodb(nameID: String): [MongoDBEventsLedger]
            nextjs(nameID: String): [NextJsEventsLedger]
        }

            # /v1/api/ledger/events/api
            type APIEventsLedger {
                createdAt: String

                ### more
            }

            # /v1/api/ledger/events/graphqlscripts
            # /v1/api/ledger/events/graphqlscripts/:graphqlscriptsnameID
            type GraphQLScriptsEventsLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/events/ec2
            # /v1/api/ledger/events/ec2/:ec2nameID
            type EC2EventsLedger {
                name: String
                nameID: String

                ### more
            }

            # /v1/api/ledger/events/apigateway
            # /v1/api/ledger/events/apigateway/:apigatewaynameID
            type ApiGatewayEventsLedger {
                name: String
                nameID: String
                dynamodb(nameID: String): [DynamoDBEventsLedger]
                s3(nameID: String): [S3EventsLedger]
                lambda(nameID: String): [LambdaEventsLedger]
            }

                # /v1/api/ledger/events/apigateway/:apigatewaynameID/dynamodb
                # /v1/api/ledger/events/apigateway/:apigatewaynameID/dynamodb/:dynamodbnameID
                type DynamoDBEventsLedger {
                    name: String
                }

                # /v1/api/ledger/events/apigateway/:apigatewaynameID/s3
                # /v1/api/ledger/events/apigateway/:apigatewaynameID/s3/:s3nameID
                type S3EventsLedger {
                    name: String
                }

                # /v1/api/ledger/events/apigateway/:apigatewaynameID/lambda
                # /v1/api/ledger/events/apigateway/:apigatewaynameID/lambda/:s3nameID
                type LambdaEventsLedger {
                    name: String
                }

            # /v1/api/ledger/events/websocket
            # /v1/api/ledger/events/websocket/:websocketnameID
            type WebsocketEventsLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/events/mongodb
            # /v1/api/ledger/events/mongodb/:mongodbnameID
            type MongoDBEventsLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/events/nextjs
            # /v1/api/ledger/events/nextjs/:nextjsnameID
            type NextJsEventsLedger {
                name: String
                nameID: String
            }

        # /v1/api/ledger/architecture
        type AppArchitectureLedger {
            api: APIArchitectureLedger
            ec2: [EC2ArchitectureLedger]
            apigateway: [ApiGatewayArchitectureLedger]
            websocket: [WebsocketArchitectureLedger]
            mongodb: [MongoDBArchitectureLedger]
            nextjs: [NextJsArchitectureLedger]
        }

            # /v1/api/ledger/architecture/api
            type APIArchitectureLedger {
                createdAt: String
            }

            # /v1/api/ledger/architecture/ec2
            # /v1/api/ledger/architecture/ec2/:ec2nameID
            type EC2ArchitectureLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/architecture/apigateway
            # /v1/api/ledger/architecture/apigateway/:apigatewaynameID
            type ApiGatewayArchitectureLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/architecture/websocket
            # /v1/api/ledger/architecture/websocket/:websocketnameID
            type WebsocketArchitectureLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/architecture/mongodb
            # /v1/api/ledger/architecture/mongodb/:mongodbnameID
            type MongoDBArchitectureLedger {
                name: String
                nameID: String
            }

            # /v1/api/ledger/architecture/nextjs
            # /v1/api/ledger/architecture/nextjs/:nextjsnameID
            type NextJsArchitectureLedger {
                name: String
                nameID: String
            }



                


